### ISSUE TITLE
Getting error srs failed load srs, try installing it

### ISSUE THREAD

**Issue by premhunt** [swerter/haraka-plugins#2]
[ERROR] [-] [srs] failed to load srs,  try installing it: npm install srs

**Comment by swerter** [comment]
Hi, 

Possible that you also need to install srs, did you try?

**Comment by Bramzor** [comment]
Had the same error. You need to install srs.js and not srs.
npm install srs.js
Error response misses the .js part

**Comment by Bramzor** [comment]
See pull request #3 for the fix.

**Comment by swerter** [comment]
Thanks! I merged your pull request.
